<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<?php
echo "\n"; 
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n"; 
echo "\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd \">\n"; 
echo " <html xmlns=\"http://www.w3.org/1999/xhtml\">\n"; 
echo " \n"; 
echo "<meta http-equiv='Content-Type' content='text/javascript; charset=utf-8' />\n"; 
echo "<head>\n"; 
echo "<style>\n"; 
echo "\n"; 
echo "</style>\n"; 
echo "\n"; 
echo "\n"; 
echo "<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />\n"; 
echo "<title>Heap Leach Optimization Visualization System</title>\n"; 
echo "<meta charset=\"utf-8\" />\n"; 
echo "\n"; 
echo "<link rel=\"stylesheet\" href=\"http://packertest.com/jquery-ui.css\" />\n"; 
echo "<link rel=\"stylesheet\" href=\"http://packertest.com/HLOVE.css\" />\n"; 
echo "<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\n"; 
echo "<script src=\"http://code.jquery.com/ui/1.9.2/jquery-ui.js\"></script>\n"; 
echo "<link rel=\"shortcut icon\" href=\"http://packertest.com/HeapVis/HLove.ico\" ></link> \n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<script>\n"; 
echo "\n"; 
echo "\$(document).ready(function(){\n"; 
echo "\n"; 
echo "var temp = \$('#dropDownDest :selected').val(), phaseVal; \n"; 
echo "var DBVal=\$('#Database :selected').val(), DBval =\$('#Database :selected').val();;\n"; 
echo "var str = 10, fac=100;\n"; 
echo "var step= \"`Oct-07`\";\n"; 
echo "var TimeTable = 0;\n"; 
echo "var AuVal, moistVal, ScaleMax = 100;\n"; 
echo "var SCALES =  [ {name:'Cnull',limit:-99}, {name: 'C20', limit:  0}, {name: 'C19', limit:0.01}, {name: 'C18', limit:1}, {name: 'C17', limit:5}, {name: 'C16', limit: 8}, {name: 'C15', limit: 12}, {name: 'C14', limit: 16}, {name: 'C13', limit: 20}, {name: 'C12', limit: 22}, {name: 'C11', limit: 26}, {name: 'C10', limit: 34}, {name:  'C9', limit: 45}, {name:  'C8', limit: 49}, {name:  'C7', limit: 53}, {name:  'C6', limit: 57}, {name:  'C5', limit: 61}, {name:  'C4', limit: 64}, {name:  'C3', limit: 68}, {name:  'C2', limit: 72}, {name:  'C1', limit: 79} ];\n"; 
echo "var newSCALES, incr;\n"; 
echo "//shortcut notiations for tables\n"; 
echo "var \$tab = \$('#tab');var \$tabR = \$('#tabR');var \$tabC = \$('#tabC');var \$scaleTab = \$('#scaleTab'); \$temp=\$('#temp');\n"; 
echo "//initial values for the tables- can get numbers from the DB\n"; 
echo "var TABLE_COUNT =15,    ROW_COUNT =41,    COL_COUNT =36;\n"; 
echo "var scaleTab='<table id=\"scaleTable\"><tbody><tr><th>Legend</th><td colspan=\"20\"></td><tr><th rowspan=\"2\">Au Recovery (% of total placed)</th><td>1</td><td>5</td><td>8</td><td>12</td><td>16</td><td>20</td><td>22</td><td>26</td><td>34</td><td>37</td><td>41</td><td>45</td><td>49</td><td>53</td><td>57</td><td>61</td><td>64</td><td>68</td><td>72</td><td>78</td></tr><tr><td colspan=\"20\"></td></tr></tbody></table>';\n"; 
echo "\n"; 
echo "var loc1 = '3D_out.html';var loc2 = 'HeapVoxel4a.html';\n"; 
echo "\$('#heapID').click(function() {\$('#myFrame').attr('src', loc1);});\n"; 
echo "\$('#feature').click(function() {\$('#myFrame').attr('src', loc2);});\n"; 
echo "\n"; 
echo "\$('#howTo').text('Choose a time step from the drop-down. Browse through the layers and cross sections.  To make a 3D representation of the 2D data, click on the \"Generate 3D\" button.  The button will remain blue during calculation.  Once the button returns to gray, the 3D representation will appear in the box below.  Click inside the box below the button to explore the data in 3D.');\n"; 
echo "\n"; 
echo "initiateData()\n"; 
echo "\n"; 
echo "function initiateData()\n"; 
echo "{\n"; 
echo "GetTimes(); //gets the column headers from the DB which represents the time steps\n"; 
echo "GetPhases();  //gets the unique values for the phases from the DB\n"; 
echo "checkDB();\n"; 
echo "\$('#amount1').val(18);  //amount 1 is the column\n"; 
echo "\$('#amount2').val(21);  //amount 2 is the row\n"; 
echo "\$('#amount3').val(1);  // amount 3 is the lift value\n"; 
echo "updateTable1(1);  //gets initial table values for lift 1\n"; 
echo "updateTable2(21);  //tabC values (top table)\n"; 
echo "updateTable3(18);	//tabR values (lower table)\n"; 
echo "//set initial values of the slider bars\n"; 
echo "instrumentHSlider( \$('#hSlider' ), \$('#amount1'));  //column output\n"; 
echo "instrumentV1Slider(\$('#vSlider1'), \$('#amount2'));  //row output\n"; 
echo "instrumentV2Slider(\$('#vSlider2'), \$('#amount3'));  //table layer\n"; 
echo "instrumentV2Slider(\$('#vSlider2a'), \$('#amount3'));  //table layer\n"; 
echo "//set the initial slider values	\n"; 
echo "\$(\"#vSlider1\").find(\"a\").text('21');\n"; 
echo "\$(\"#hSlider\").find(\"a\").text('18');\n"; 
echo "\$(\"#vSlider2\").find(\"a\").text('1');\n"; 
echo "\$(\"#vSlider2a\").find(\"a\").text('1');\n"; 
echo "updateHighlightedCell();\n"; 
echo "}\n"; 
echo "\n"; 
echo "function updateDB()\n"; 
echo "{\n"; 
echo "temp  = \$('#dropDownDest').val();\n"; 
echo "DBVal = \$('#Database').val();\n"; 
echo "updateTable1(\$('#amount3').val());\n"; 
echo "updateTable3(\$('#amount1').val()); //tabR\n"; 
echo "updateTable2(\$('#amount2').val()); //tabC\n"; 
echo "updateHighlightedCell();\n"; 
echo "}\n"; 
echo "\n"; 
echo "function checkDB()\n"; 
echo "{\n"; 
echo "	    if(DBVal=='`dat`')\n"; 
echo "	// TimeTable = 0 for all tables that contain time series data with the same time step column names\n"; 
echo "		{TimeTable = 0;\n"; 
echo "		}\n"; 
echo "		else if(DBVal=='`Moisture`')\n"; 
echo "		{TimeTable = 0;\n"; 
echo "		}\n"; 
echo "		else if(DBVal=='`Gold`')\n"; 
echo "		{TimeTable = 0;\n"; 
echo "		}  \n"; 
echo "		//if the TimeTable=1 this means that there is oonly one 'time step' in the data. Column values must equal the table name\n"; 
echo "		else if(DBVal=='`Inventory`')\n"; 
echo "		{TimeTable = 1;\n"; 
echo "		}\n"; 
echo "		else if(DBVal=='`Solution`')\n"; 
echo "		{TimeTable = 1;\n"; 
echo "		}\n"; 
echo "		//else if(DBVal=='`ColumnElev`')\n"; 
echo "		//{TimeTable = 1;\n"; 
echo "		//}\n"; 
echo "		else if(DBVal=='`CellThickness`')\n"; 
echo "		{TimeTable = 1;\n"; 
echo "		}\n"; 
echo "		else if(DBVal=='`LoadedThickness`')\n"; 
echo "		{TimeTable = 1;\n"; 
echo "		}\n"; 
echo "		//else if(DBVal=='`LinerElevation`')\n"; 
echo "		//{TimeTable = 1;\n"; 
echo "		//}\n"; 
echo "		else if(DBVal=='`KPrime`')\n"; 
echo "		{TimeTable = 1;\n"; 
echo "		}\n"; 
echo "		//else if(DBVal=='`PhaseID`')\n"; 
echo "		//{TimeTable = 1;\n"; 
echo "		//}\n"; 
echo "}\n"; 
echo "\n"; 
echo "\$('#Database').change(function(e){  //changes the time step to display using the dropdown\n"; 
echo "	updateDB();\n"; 
echo "}).change();\n"; 
echo "\n"; 
echo "\$('#dropDownDest').change(function(e){  //updates the tables to pull from the desired database using the dropdown\n"; 
echo "	updateDB();\n"; 
echo "}).change();\n"; 
echo "\n"; 
echo "function GetPhases()\n"; 
echo "{\n"; 
echo "	if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "				document.getElementById(\"phaseDrop\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "		\n"; 
echo "        xmlhttp.open(\"GET\",\"phases.php\", false);		\n"; 
echo "		xmlhttp.send();\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function GetTimes()  //this gets the \"time values\" for any time series data\n"; 
echo "{\n"; 
echo "	if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"dropDownDest\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "		xmlhttp.open(\"GET\",\"GetColNames.php\", false);\n"; 
echo "		\n"; 
echo "		xmlhttp.send();\n"; 
echo "\n"; 
echo "		\$(\"#dropDownDest option\").slice(0, 5).remove();  //removes the first 7 entries that are not time steps\n"; 
echo "}\n"; 
echo "\n"; 
echo "function GetTable1(value)  //main table values\n"; 
echo "{	\n"; 
echo "if(TimeTable == 0)\n"; 
echo "	{\n"; 
echo "\n"; 
echo "     if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"tab\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "\n"; 
echo "        xmlhttp.open(\"GET\",\"PlanView.php?DBVal=\" + DBVal +\"&step=\" + temp + \"&lift=\" + value, false);\n"; 
echo "		\n"; 
echo "		xmlhttp.send();\n"; 
echo "	\n"; 
echo "	}\n"; 
echo "if(TimeTable == 1)\n"; 
echo "	{\n"; 
echo "		 if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"tab\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "\n"; 
echo "        xmlhttp.open(\"GET\",\"PlanView_Single.php?DBVal=\" + DBVal +\"&step=\" + DBVal + \"&lift=\" + value, false);\n"; 
echo "		\n"; 
echo "		xmlhttp.send();\n"; 
echo "		}\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "function GetTable2(value)\n"; 
echo "{\n"; 
echo "if(TimeTable == 0)\n"; 
echo "	{		\n"; 
echo "	  if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"tabC\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "		                  \n"; 
echo "        xmlhttp.open(\"GET\",\"XZView.php?DBVal=\" + DBVal +\"&step=\" + temp + \"&lift=\" + value, false);\n"; 
echo "		\n"; 
echo "		xmlhttp.send();\n"; 
echo "		}\n"; 
echo "		\n"; 
echo "if(TimeTable == 1)\n"; 
echo "	{\n"; 
echo "	if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"tabC\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "\n"; 
echo "        xmlhttp.open(\"GET\",\"XZView_Single.php?DBVal=\" + DBVal +\"&step=\" + DBVal + \"&lift=\" + value, false);\n"; 
echo "		\n"; 
echo "		xmlhttp.send();\n"; 
echo "		}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function GetTable3(value)\n"; 
echo "{	\n"; 
echo "if(TimeTable == 0)\n"; 
echo "	{		\n"; 
echo "	 if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"tabR\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "                  \n"; 
echo "        xmlhttp.open(\"GET\",\"YZView.php?DBVal=\" + DBVal +\"&step=\" + temp + \"&lift=\" + value, false);\n"; 
echo "		\n"; 
echo "		xmlhttp.send();\n"; 
echo "	}\n"; 
echo "	\n"; 
echo "if(TimeTable == 1)\n"; 
echo "	{\n"; 
echo "	if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"tabR\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "\n"; 
echo "        xmlhttp.open(\"GET\",\"YZView_Single.php?DBVal=\" + DBVal +\"&step=\" + DBVal + \"&lift=\" + value, false);\n"; 
echo "		\n"; 
echo "		xmlhttp.send();\n"; 
echo "		}\n"; 
echo "}\n"; 
echo "\n"; 
echo "function GetCellInfo(Col, Row, Lay) //This gets the information from the DB for each cell\n"; 
echo "{	\n"; 
echo "\n"; 
echo "if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"info\").innerHTML = xmlhttp.responseText;\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "		\n"; 
echo "        temp = \$('#dropDownDest :selected').val();\n"; 
echo "        xmlhttp.open(\"GET\",\"CellValues.php?temp=\" + temp + \"&Row=\" + Row +\"&Lay=\" + Lay + \"&Col=\" + Col, false);\n"; 
echo "		\n"; 
echo "		xmlhttp.send();\n"; 
echo "}\n"; 
echo "\n"; 
echo "var tdEnlargedCssMap = {    border: 'none', position: 'fixed',    left: '620px',    top: '8px',    'font-size': '18px', 'color': 'yellow' }  //this goes along with the function below\n"; 
echo "\n"; 
echo "\$('body').on('mouseenter', 'table td', function() {\n"; 
echo "		\$(this).closest('table').append(\n"; 
echo " 		\$(this).clone().addClass('cloned-element').css(tdEnlargedCssMap).show());\n"; 
echo "		})\n"; 
echo "		\n"; 
echo "\$('body').on('mouseleave', 'table td', function(){\n"; 
echo "		\$(this).closest('table').find('.cloned-element').remove();\n"; 
echo " 		});\n"; 
echo "  \n"; 
echo "function getTableInfo(){\n"; 
echo "	var tr = \$(this).parent()\n"; 
echo "	for (var i = 0; i < tr.children().length; i++) {\n"; 
echo "		if (tr.children().get(i) == this) {\n"; 
echo "			var column = i;\n"; 
echo "			break;\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	var tbody = tr.parent();\n"; 
echo "	for (var j = 0; j < tbody.children().length; j++) {\n"; 
echo "		if (tbody.children().get(j) == tr.get(0)) {\n"; 
echo "			var row = j;\n"; 
echo "			break;\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "}\n"; 
echo "\n"; 
echo "\$('body')  //displays the information about the cell\n"; 
echo ".on('click','#tab td', function(){\n"; 
echo "getTableInfo();\n"; 
echo "var iCol =\$(this).closest('tr td').prevAll('tr td').length;\n"; 
echo "var iRow = \$(this).closest('tr').prevAll('tr').length;\n"; 
echo "var iLay =  parseInt(\$('#amount3').val(), 10);\n"; 
echo "var tdCol = \$(this).closest('tr td').prevAll('tr td').css('border');\n"; 
echo "var tdClass = \$(this).siblings('tr td').attr('class');\n"; 
echo "realRow =41-iRow-1;\n"; 
echo "realCol = iCol+1;\n"; 
echo "GetCellInfo(realCol, realRow, iLay);\n"; 
echo "\$('#amount1').val(realCol);\n"; 
echo "\$('#amount2').val(realRow);\n"; 
echo "updateTable3(realCol);\n"; 
echo "updateTable2(realRow);\n"; 
echo "updateHighlightedCell();\n"; 
echo "\$('#vSlider1').slider({ animate:true,value: realRow})\n"; 
echo "\$('#hSlider').slider({  animate:true,value: realCol});\n"; 
echo "\$(\"#vSlider1\").find(\"a\").text(realRow);\n"; 
echo "\$(\"#hSlider\").find(\"a\").text(realCol);\n"; 
echo "})\n"; 
echo "\n"; 
echo "\$('body')\n"; 
echo ".on('click','#tabR td', function(){  \n"; 
echo "getTableInfo();\n"; 
echo "var iCol =\$(this).closest('tr td').prevAll('tr td').length;\n"; 
echo "var iLay = \$(this).closest('tr').prevAll('tr').length;\n"; 
echo "var iRow =  parseInt(\$('#amount1').val(), 10);\n"; 
echo "realRow =41-iCol;\n"; 
echo "realLay =15-iLay-1;\n"; 
echo "GetCellInfo(iRow, realRow,realLay);\n"; 
echo "\$('#amount3').val(realLay);\n"; 
echo "\$('#amount2').val(realRow);\n"; 
echo "updateTable1(realLay);\n"; 
echo "updateTable2(realRow);\n"; 
echo "updateHighlightedCell();\n"; 
echo "\$('#vSlider1').slider({ animate:true,value: realRow});\n"; 
echo "\$('#vSlider2').slider({ animate:true,value: realLay});\n"; 
echo "\$('#vSlider2a').slider({animate:true,value: realLay});\n"; 
echo "\$(\"#vSlider1\").find(\"a\").text(realRow);\n"; 
echo "\$(\"#vSlider2\").find(\"a\").text(realLay);\n"; 
echo "\$(\"#vSlider2a\").find(\"a\").text(realLay);    \n"; 
echo "})\n"; 
echo "\n"; 
echo "\$('body')\n"; 
echo ".on('click','#tabC td', function(){ \n"; 
echo "getTableInfo(); \n"; 
echo "var iCol =\$(this).closest('tr td').prevAll('tr td').length;\n"; 
echo "var iLay = \$(this).closest('tr').prevAll('tr').length;\n"; 
echo "var iRow =  parseInt(\$('#amount2').val(), 10);\n"; 
echo "realCol = iCol+1;\n"; 
echo "realLay = 15-iLay-1;\n"; 
echo "GetCellInfo(realCol, iRow, realLay);\n"; 
echo "\$('#amount3').val(realLay);\n"; 
echo "\$('#amount1').val(realCol);\n"; 
echo "updateTable1(realLay);\n"; 
echo "updateTable3(realCol);\n"; 
echo "updateHighlightedCell();\n"; 
echo "\$('#hSlider').slider({  animate:true,value: realCol});\n"; 
echo "\$('#vSlider2').slider({ animate:true,value: realLay});\n"; 
echo "\$('#vSlider2a').slider({animate:true,value: realLay});\n"; 
echo "\$(\"#hSlider\").find(\"a\").text(realCol);\n"; 
echo "\$(\"#vSlider2\").find(\"a\").text(realLay);\n"; 
echo "\$(\"#vSlider2a\").find(\"a\").text(realLay);  \n"; 
echo "})\n"; 
echo "\n"; 
echo "function reverseSlider(val, max) { return (max - val );}\n"; 
echo "\n"; 
echo "function updateTable1(Sval) {  //main plan view table\n"; 
echo "	checkDB();\n"; 
echo "	GetTable1(Sval);\n"; 
echo "		\$tab.children().find('td').each(function() {\n"; 
echo "		var \$td = \$(this),score = parseInt(\$td .text(), 10);\n"; 
echo " 		\$.each(SCALES, function(i, scale) {\n"; 
echo "			if (score <= scale.limit) {\n"; 
echo "			\$td.addClass(scale.name);\n"; 
echo "			return false;\n"; 
echo "			}\n"; 
echo " 		});\n"; 
echo "	});\n"; 
echo "}\n"; 
echo "\n"; 
echo "function updateTable2(Sval) {  //tabC (upper table) colum section 41 in length\n"; 
echo "	checkDB();\n"; 
echo "	GetTable2(Sval);\n"; 
echo "	\$tabC.children().find('td').each(function() {\n"; 
echo "		var \$td = \$(this),score = parseInt(\$td .text(), 10);\n"; 
echo "		\$.each(SCALES, function(i, scale) {\n"; 
echo "			if (score <= scale.limit) {\n"; 
echo "			\$td.addClass(scale.name);\n"; 
echo "			return false;\n"; 
echo "			}\n"; 
echo "		});\n"; 
echo "	}); \n"; 
echo "}\n"; 
echo "\n"; 
echo "function updateTable3(Sval) {  //tabR (lower table) row section 36 in length\n"; 
echo "	checkDB();\n"; 
echo "	GetTable3(Sval);\n"; 
echo "	\$tabR.children().find('td').each(function() {\n"; 
echo "		var \$td = \$(this), score = parseInt(\$td .text(), 10);\n"; 
echo "		\$.each(SCALES, function(i, scale) {\n"; 
echo "			if (score <= scale.limit) {\n"; 
echo "			\$td.addClass(scale.name);\n"; 
echo "			return false;\n"; 
echo "			}        \n"; 
echo "		});    \n"; 
echo "	}); \n"; 
echo "} \n"; 
echo "\n"; 
echo "function updateHighlightedCell() {  //this updates the crosshairs on all three tables \n"; 
echo "var iCol =      parseInt(\$('#amount1').val(), 10);\n"; 
echo "var iRow =    - parseInt(\$('#amount2').val(), 10);\n"; 
echo "var iLayer =  - parseInt(\$('#amount3').val(), 10);\n"; 
echo "var \$table = \$tab.children(), \$tableR= \$tabR.children(), \$tableC= \$tabC.children();\n"; 
echo "\n"; 
echo "\$table.find('td').removeClass('highlighted');//crosshair on main table\n"; 
echo "\$table.find('tr').find('td:eq(' + (iCol-1) + ')').addClass('highlighted');\n"; 
echo "\$table.find('tr:eq(' + iRow + ')').find('td').addClass('highlighted');\n"; 
echo "\n"; 
echo "\$tableR.find('td').removeClass('highlighted');//crosshair on row table\n"; 
echo "\$tableR.find('tr').find('td:eq(' + (iRow) + ')').addClass('highlighted');\n"; 
echo "\$tableR.find('tr:eq(' + (iLayer) + ')').find('td').addClass('highlighted');\n"; 
echo "\n"; 
echo "\$tableC.find('td').removeClass('highlighted');//crosshair on column table\n"; 
echo "\$tableC.find('tr').find('td:eq(' + (iCol-1) + ')').addClass('highlighted');\n"; 
echo "\$tableC.find('tr:eq(' + (iLayer) + ')').find('td').addClass('highlighted');\n"; 
echo "}\n"; 
echo "\n"; 
echo "function instrumentHSlider(\$slider, \$boundInput) {\n"; 
echo "	var sliderH = \$slider.slider({ orientation: 'horizontal',range:'min', min: 1, max: COL_COUNT, value: 18, animate:1000, slide: function (event, ui) {\n"; 
echo "		\$boundInput.val(ui.value);\n"; 
echo "		posVal=\$slider.slider('value');  //gets number for row or column\n"; 
echo "		updateTable3(ui.value);  //updates the info in the tabR div\n"; 
echo " 		updateHighlightedCell();\n"; 
echo "		\$(this).find('a').text(ui.value);\n"; 
echo "		}\n"; 
echo "	});\n"; 
echo "	\$boundInput.val(\$slider.slider('value'));\n"; 
echo "}\n"; 
echo "\n"; 
echo "function instrumentV1Slider(\$slider, \$boundInput) {\n"; 
echo "	var sliderV1 = \$slider.slider({ orientation: 'vertical',range: 'max', min: 1, max: ROW_COUNT, value: 21,animate:1000,slide: function (event, ui) {\n"; 
echo "		\$boundInput.val(ui.value);\n"; 
echo "    	posVal=\$slider.slider('value');  //gets number for row or column\n"; 
echo "		updateTable2(ui.value);  //updates the info in the tabC div\n"; 
echo "		updateHighlightedCell();\n"; 
echo "		\$(this).find('a').text(ui.value);\n"; 
echo "		}\n"; 
echo "	})\n"; 
echo "	\$boundInput.val(\$slider.slider('value'), ROW_COUNT);\n"; 
echo "}\n"; 
echo "\n"; 
echo "function instrumentV2Slider(\$slider, \$boundInput) {\n"; 
echo "	var posVal;\n"; 
echo " 	var sliderV2= \$slider.slider({ orientation: 'vertical',range: 'max', min: 1, max: TABLE_COUNT, value: 1,    animate:1000, slide: function (event, ui) {\n"; 
echo " 		\$boundInput.val(ui.value);\n"; 
echo "		posVal=\$slider.slider('value');\n"; 
echo "		\$('#vSlider2a').slider('option', 'value', ui.value);\n"; 
echo "		\$('#vSlider2').slider('option', 'value', ui.value); \n"; 
echo "		updateTable1(ui.value);\n"; 
echo "		updateHighlightedCell();\n"; 
echo "		\$(\"#vSlider2\").find(\"a\").text(ui.value);\n"; 
echo "        \$(\"#vSlider2a\").find(\"a\").text(ui.value);		}\n"; 
echo "    });\n"; 
echo "	\$boundInput.val(\$slider.slider('value'), TABLE_COUNT);\n"; 
echo "\n"; 
echo "}\n"; 
echo "\n"; 
echo "\$scaleTab.children().find('td').each(function() {\n"; 
echo "	var \$td = \$(this),  score = parseInt(\$td .text(), 10);\n"; 
echo "	\$.each(SCALES, function(i, scale) {\n"; 
echo " 		if (score <= scale.limit) {\n"; 
echo " 		\$td.addClass(scale.name);\n"; 
echo "		return false;\n"; 
echo "		} \n"; 
echo "	});\n"; 
echo "});\n"; 
echo "\n"; 
echo "\n"; 
echo "\$('#Gen3D').on('click', function (e) {  //generates the 3D representation in the iFrame using Heapvoxel5Ts.html\n"; 
echo "	e.preventDefault();\n"; 
echo "	//this makes the arrays for 3D and saves as local storage\n"; 
echo "    \n"; 
echo "\n"; 
echo "	checkDB(); \n"; 
echo "	if(TimeTable == 0)\n"; 
echo "	{\n"; 
echo "	 if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"myFrame\").innerHTML = \"Please Wait\";\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "		var step = \$('#dropDownDest :selected').val();\n"; 
echo "        DBVal = \$('#Database').val();\n"; 
echo "		fac = 100;\n"; 
echo "        xmlhttp.open(\"GET\",\"Make3D.php?DBVal=\" + DBVal +\"&step=\" + step +\"&fac=\" + fac , false);\n"; 
echo "\n"; 
echo "		xmlhttp.send();\n"; 
echo "	}\n"; 
echo "else if(TimeTable == 1)\n"; 
echo "	{\n"; 
echo "	if (window.XMLHttpRequest) {\n"; 
echo "            // code for IE7+, Firefox, Chrome, Opera, Safari\n"; 
echo "            xmlhttp = new XMLHttpRequest();\n"; 
echo "        } else {\n"; 
echo "            // code for IE6, IE5\n"; 
echo "            xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\n"; 
echo "        }\n"; 
echo "        xmlhttp.onreadystatechange = function() {\n"; 
echo "            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\n"; 
echo "                document.getElementById(\"myFrame\").innerHTML = \"Please Wait\";\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "		\n"; 
echo "        DBVal = \$('#Database').val();\n"; 
echo "        fac = 1;\n"; 
echo "        xmlhttp.open(\"GET\",\"Make3D.php?DBVal=\" + DBVal +\"&step=\" + DBVal +\"&fac=\" + fac , false);\n"; 
echo "\n"; 
echo "		xmlhttp.send();\n"; 
echo "	}\n"; 
echo "	 \n"; 
echo "	\$('#myFrame').attr('src', loc1);\n"; 
echo "	\n"; 
echo "});\n"; 
echo "\n"; 
echo "\$('#ShowInfo').click(function(e){  \n"; 
echo "	alert(\"Heap Leach Optimization (made) Very Easy  (HLOVE)                   This model depicts a Heap Leach Optimization Simulation.  This model was produced using GoldSim from 'real physical properties' input into the model.  The model then predicts, based on time series application of leaching solution, how much gold has leached and remains in the heap.  Tweaking application rates and changing other pysical properties of the model can allow a client to more efficiently load ore, change agglomeration properties, and lixiviant application rates and concentrations to ensure the highest concentration of leached gold ore.  This model shows preliminary data and fabricated data and is for demonstration purposes only.\")\n"; 
echo "		\n"; 
echo "	}); \n"; 
echo "\n"; 
echo "});\n"; 
echo "\n"; 
echo "</script>\n"; 
echo "<body>\n"; 
echo "<input type='text' id='amount1' />\n"; 
echo "<div id='hSlider' style='width:637px;'></div>\n"; 
echo "<div id='vSlider1' style='height:660px;'></div>\n"; 
echo "<input type='text' id='amount2' />\n"; 
echo "<div id='vSlider2' style='height:120px;'></div>\n"; 
echo "<input type='text' id='amount3' />\n"; 
echo "<div id='vSlider2a' style='height:120px;'></div>\n"; 
echo "<div id='tab' > </div>\n"; 
echo "<div id='tabC' class='smGrid'></div> \n"; 
echo "<div id='tabR' class='smGrid' ></div>\n"; 
echo "<div id='temp' > </div>\n"; 
echo "<div id='L1'><b>Col:</b></div>\n"; 
echo "<div id='L2'><b>Row:</b></div>\n"; 
echo "<div id='L3'><b>Cell Data</b></div>\n"; 
echo "<div id='L4'><b>Cell Value</b></div> \n"; 
echo "<div id='L5'><b>Layer:</b></div>\n"; 
echo "<div id='Hlabel'>Column Cross Section</div>\n"; 
echo "<div id='Vlabel'>Row Cross Section</div>\n"; 
echo "<button id='Gen3D' >Generate 3D</button>\n"; 
echo "<div id='info' style='height:130px'> <center>click on a cell to view data</center></div>\n"; 
echo "<div id='howTo' > </div>\n"; 
echo "<div id='scaleTab' style='width:495px;'><table id='scaleTable'><tbody><tr><th>Legend</th><th colspan='20'></th></tr><tr><th >\n"; 
echo "<select id= \"Database\">\n"; 
echo "<option value=\"`dat`\">Au Recovery (% of total placed)</option>\n"; 
echo "<option value=\"`Moisture`\">Ore Gravimetric H2O Content (%)</option>\n"; 
echo "<option value=\"`Inventory`\">Au Inventory (troy oz)</option>\n"; 
echo "<option value=\"`Solution`\">Solution to Ore Ratio</option>\n"; 
echo "\n"; 
echo "\n"; 
echo "<option value=\"`LoadedThickness`\">Loaded Cell Thickness (ft)</option>\n"; 
echo "\n"; 
echo "<option value=\"`KPrime`\">Au Extraction k' Value (x1000)</option>\n"; 
echo "\n"; 
echo "\n"; 
echo "</select></th><td>0.1</td><td>1</td><td>5</td><td>8</td><td>12</td><td>16</td><td>20</td><td>22</td><td>26</td><td>34</td><td>41</td><td>45</td><td>49</td><td>53</td><td>57</td><td>61</td><td>64</td><td>68</td><td>72</td><td>78</td></tr></tbody></table></div>\n"; 
echo "<iframe id=\"myFrame\"></iframe>\n"; 
echo "<textarea id=\"live1\" style=\"width:440px;height:70px\"></textarea>\n"; 
echo "<select id= \"dropDownDest\"></select>\n"; 
echo "<select id= \"phaseDrop\"></select>\n"; 
echo "<button id='ShowInfo' >About Model</button>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>
<body>
</body>
</html>